name: Test

on:
  push:
    branches: [development]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: "This is my Job Bariable"
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multiline script
        # run: |
        #   echo Add other actions to build,
        #   echo test, and drploy your project.
        
        env: 
          STEP_VARIABLE: "This is my step variable"

        run: |
          echo $JOB_VARIABLE
          echo $STEP_VARIABLE
